# config.yaml

# File paths
data_format: "parquet"
input_file_path: ""
output_file_path: ""

# Columns names
datetime_column: "Date"
symbol_column: "Symbol"
feature_columns: [ 'open', 'high', 'low', 'close', 'volume' ]
target_column: "Label"

# Model selection
model: "xgboost"  # options: linear, xgboost, rf

# Hyperparameters foe each model
model_params:
  linear:
    type: "linear_regression"
    parameters: { }
  
  xgboost:
    type: "xgboost"
    parameters:
      objective: "reg:squarederror"
      max_depth: 3
      learning_rate: 0.001
      n_estimators: 4000

  rf:
    type: "random_forest"
    parameters:
      n_estimators: 1000
      max_depth: 5
      random_state: 42